# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  tests: './XUnitTests/XUnitTests.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dotNetFramework: 'net6.0'
  dotNetVersion: '6.0.x'

steps:
- script: npm ci
  workingDirectory: ./StudentoMainProject/
  displayName: 'npm ci'

- script: npm run build
  workingDirectory: ./StudentoMainProject/
  displayName: 'npm build'

- task: UseDotNet@2
  inputs:
    version: $(dotNetVersion)
    installationPath: $(Agent.ToolsDirectory)/dotnet
- script: dotnet test --configuration $(buildConfiguration) $(tests)
  displayName: 'Run unit tests'
  
- task: UseDotNet@2
  inputs:
    version: $(dotNetVersion)
    installationPath: $(Agent.ToolsDirectory)/dotnet
- script: dotnet publish --configuration $(buildConfiguration) -o $(build.artifactstagingdirectory)\WebApp.zip
  displayName: 'Build Studento Web App'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'