trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  tests: './XUnitTests/XUnitTests.csproj'
  mainProject: './StudentoMainProject/StudentoMainProject.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: npm ci
  workingDirectory: ./StudentoMainProject/
  displayName: 'npm ci'

- script: npm run build
  workingDirectory: ./StudentoMainProject/
  displayName: 'npm build'

- script: dotnet build $(mainProject) -c $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '-c $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    projects: '$(mainProject)'
    arguments: '-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'